### ISSUE TITLE
Huge performance issue while scrolling

### ISSUE THREAD

**Issue by Reak45** [m1entus/MZFormSheetController#157]
Hi, I am trying to use MZFormSheetController to display a tableView controller. It works, but when I try to scroll the table, huge response delays occures. The same thing happens when I use view controller with scroller in it. Here the code:

UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"Main" bundle:nil];
    SuperTableViewController *vc = [storyboard instantiateViewControllerWithIdentifier:@"tableViewController"];
    
    MZFormSheetController *formSheet = [[MZFormSheetController alloc] initWithViewController:vc];
    
    formSheet.transitionStyle = MZFormSheetTransitionStyleSlideFromBottom;
    formSheet.presentedFormSheetSize = CGSizeMake(self.getScreenWidth * 0.9, self.getScreenHeight * 0.8);
    [formSheet presentAnimated:YES completionHandler:^(UIViewController *presentedFSViewController) {
        
    }];

Please help

**Comment by m1entus** [comment]
Without MZFormSheetController is working smooth? Turn off blurring and check how it is going, open Time Profiler check what is consuming most time...

**Comment by Reak45** [comment]
Unfortunately, turning blurring off did not resolved the issue.

**Comment by m1entus** [comment]
Turn off layer shadow on presentedFSController, it will help

**Comment by palcalde** [comment]
I am experiencing the same issue. MZFormSheetPresentationController withn iOS8 works perfect since uses the native way to show modals with presentationStyle etc. 

However, we are forced to use MZFormSheetController for iOS7 and this causes huge delay problems on iphone4. I've tested showing the same controller using regular transitionStyle in ios 7 and there isn't any delay. Must be something related with the fact that the library presents a new window ec..

**Comment by palcalde** [comment]
Yes @m1entus is right, setting :

formSheet.shadowRadius = 0;
        formSheet.shadowOpacity = 0;
        formSheet.cornerRadius = 0;

Works great ! :+1:
